### ISSUE TITLE
Verbindung mit Xerces-C 3.2 

### ISSUE THREAD

**Issue by angelablancovogt79** [tschuettenberg/isybau2qgep#2]
Guten Tag Herr Schüttenberg,

ich möchte Sie fragen, wie ich die Verbindung mit Xerces-C 3.2 überprüfen kann?
Ich möchte ein ISYBAU-XML Datei in PostGIS einlesen. Ich habe den GMLAS Treiber in QGIS importiert. 
Vielen Dank
Freundliche Grüße

**Comment by tschuettenberg** [comment]
Unter der Annahme, dass Sie QGIS 3.4 verwenden, haben Sie damit GDAL 2.3.2 (mit GMLAS).  -> OSGeo4W Shell: `ogrinfo --version`

Bei der QGIS-Installation sollte IMHO auch das notwendige xerces-c 3.2.0 gleich mitkommen, ansonsten ist es unter Libs im OSGeo4W-Installer auszuwählen - bzw. zu sehen, ob es da schon installiert ist.
